export const ui = {
  shell: "mx-auto w-[min(calc(100%-2rem),92rem)] py-[clamp(2rem,5vw,5rem)] max-[560px]:w-[min(calc(100%-1rem),92rem)]",
  topbar: "border-b border-line bg-panel",
  topbarInner: "mx-auto flex min-h-16 w-[min(calc(100%-2rem),92rem)] items-center justify-between gap-4 max-[560px]:w-[min(calc(100%-1rem),92rem)]",
  brand: "min-h-0 font-mono font-semibold no-underline [&>span]:text-signal",
  nav: "flex gap-4 max-[560px]:gap-2.5 [&>a]:min-h-0",
  eyebrow: "m-0 mb-3 font-mono text-xs uppercase tracking-wider text-cyan",
  title: "m-0 max-w-[15ch] text-[clamp(2.7rem,7vw,6.8rem)] leading-tight tracking-[-.055em]",
  sectionTitle: "m-0 text-[clamp(1.5rem,3vw,2.6rem)] leading-tight tracking-[-.035em]",
  lede: "my-5 max-w-3xl text-[clamp(1.1rem,2vw,1.35rem)] text-muted",
  terminal: "border border-line bg-panel font-mono text-[.82rem] shadow-[8px_8px_0_#080b0c]",
  terminalHeader: "flex justify-between border-b border-line px-3 py-2 text-xs text-muted",
  terminalBody: "p-5 leading-loose",
  button: "inline-flex min-h-11 items-center justify-center rounded border border-line bg-panel px-4 py-3 font-bold text-ink no-underline hover:border-signal",
  primaryButton: "inline-flex min-h-11 items-center justify-center rounded border border-[#a96200] bg-signal px-4 py-3 font-bold text-[#171006] no-underline",
  input: "min-h-11 w-full rounded-sm border border-line bg-[#090d0f] px-3 py-3 text-ink placeholder:text-muted",
  screenHead: "grid grid-cols-[minmax(0,1fr)_minmax(17rem,.4fr)] gap-8 border-b border-line pb-6 max-[800px]:grid-cols-1",
  dataGrid: "mt-6 grid grid-cols-4 border border-line max-[800px]:grid-cols-2 max-[560px]:grid-cols-1",
  datum: "min-w-0 border-r border-line bg-panel p-4 font-mono last:border-r-0 max-[560px]:border-r-0 max-[560px]:border-t max-[560px]:first:border-t-0",
  alert: "mt-5 border border-[#a96200] bg-[#251b0d] p-4 text-[#e6d7bf] [&>strong]:text-[#ffc66d] [&>p]:m-1",
  positive: "text-positive",
  signal: "text-signal",
  negative: "text-negative",
  muted: "text-muted",
} as const;
