import Link from "next/link";
import { DemoTimeline } from "@/components/demo-timeline";
import { getFixtureCommits, getFixtureRepository } from "@/features/fixtures/repository-fixtures";
import { ui } from "@/lib/ui";

export default async function RepositoryPage() {
  const [repository, commits] = await Promise.all([getFixtureRepository(), getFixtureCommits()]);
  const { snapshot } = repository;
  return <><header className={ui.topbar}><div className={ui.topbarInner}><Link className={ui.brand} href="/"><span aria-hidden="true">&gt;_</span> reporeplay</Link><nav aria-label="Repository" className={ui.nav}><Link href="/">Import</Link><Link href="/case-study">Case study</Link></nav></div></header><main className={ui.shell} id="main-content"><header className="flex items-end justify-between gap-8 border-b border-line pb-5 max-[800px]:flex-col max-[800px]:items-start"><div><p className={ui.eyebrow}>active snapshot</p><h1 className="m-0 break-words text-[clamp(2.2rem,5vw,4.5rem)] leading-tight">{repository.owner}/{repository.name}</h1><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 font-mono text-xs text-muted"><span>branch {repository.defaultBranch}</span><span>root {repository.selectedAppRoot}</span><span>{snapshot.firstParentCommitCount} commits</span><span>detectors v{snapshot.versions.routeDetector}</span></div></div><div className="text-right font-mono text-xs leading-loose text-muted max-[800px]:text-left">root {snapshot.rootSha}<br />head {snapshot.headSha}<br />activated {new Date(snapshot.processedAt).toLocaleString("en-GB")}</div></header><section className={ui.dataGrid} aria-label="Repository summary"><Fact label="history" value={`${snapshot.firstParentCommitCount} complete`} /><Fact label="routes at head" value={String(snapshot.routeCount)} /><Fact label="declared dependencies" value={String(snapshot.dependencyCount)} /><Fact label="coverage warnings" value={`${snapshot.warnings.length} review`} /></section>{snapshot.warnings.map((warning) => <div className={ui.alert} key={warning.code}><strong>Route coverage warning.</strong><p>{warning.message} <code>{warning.path}</code></p></div>)}<DemoTimeline commits={commits} /></main></>;
}
function Fact({ label, value }: { label: string; value: string }) { return <div className={ui.datum}><span className="block text-xs uppercase text-muted">{label}</span><strong className="mt-1 block break-words text-lg">{value}</strong></div>; }
