"use client";

import Link from "next/link";
import { useState } from "react";
import type { ProcessingRunView } from "@/server/contracts/api";
import { ui } from "@/lib/ui";

const steps=["Discover first-parent history","Fetch commit evidence","Classify commit messages","Detect dependency transitions","Detect route transitions","Validate and activate snapshot"];
export function ProcessingView({run}:{run:ProcessingRunView}){const[cancelled,setCancelled]=useState(false);return <section aria-labelledby="processing-title"><header className={ui.screenHead}><div><p className={ui.eyebrow}>run {run.id} / lease active</p><h1 className={ui.sectionTitle} id="processing-title">Processing durable evidence.</h1></div><p className="m-0 text-muted"><code>acme/ledger</code><br/><code>main@9d8e7f6</code><br/><code>apps/storefront</code></p></header><div className="mt-8 grid grid-cols-[minmax(0,1fr)_20rem] gap-8 max-[800px]:grid-cols-1"><div><div className="border border-line bg-[#090d0f]" aria-label="Processing steps">{steps.map((step,index)=><div className={`grid grid-cols-[3rem_minmax(0,1fr)_auto] gap-4 border-b border-soft p-4 font-mono text-xs last:border-b-0 max-[560px]:grid-cols-1 ${index===1&&!cancelled?"bg-[#1d1a12]":""}`} key={step}><span>{String(index+1).padStart(2,"0")}</span><strong>{step}</strong><span className={index===0?ui.positive:index===1&&!cancelled?ui.signal:ui.muted}>{cancelled?"cancelled":index===0?"complete":index===1?`${run.processedCommits} / ${run.expectedCommits}`:"queued"}</span></div>)}</div><p className="mt-3 font-mono text-xs text-muted" role="status" aria-live="polite">{cancelled?"Run cancelled. No staged output was activated.":"Checkpoint persisted. Closing this page will not stop the worker."}</p></div><aside className={ui.terminal}><div className={ui.terminalHeader}><span>worker</span><span className={cancelled?ui.signal:ui.positive}>{cancelled?"stopped":"healthy"}</span></div><div className={ui.terminalBody}><div>attempt {run.attemptCount} / 4</div><div>github quota sufficient</div><div>previous snapshot none</div></div><div className="flex flex-col gap-3 px-4 pb-4">{cancelled?<button className={ui.button} onClick={()=>setCancelled(false)} type="button">Retry run</button>:<button className={ui.button} onClick={()=>setCancelled(true)} type="button">Cancel run</button>}<Link className={ui.primaryButton} href="/repositories/demo">Preview completed run</Link></div></aside></div></section>}
