"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import type { CommitEvidence } from "@/server/contracts/api";

export function Timeline({ commits }: { commits: CommitEvidence[] }) {
  const [query, setQuery] = useState("");
  const [event, setEvent] = useState("ALL");
  const visible = useMemo(() => commits.filter((commit) => commit.message.toLowerCase().includes(query.toLowerCase()) && (event === "ALL" || (event === "ROUTE" ? commit.routeChanges.length : commit.dependencyChanges.length))), [commits, event, query]);
  return <div className="workspace"><aside className="filters" aria-label="Timeline filters"><h2>Filter record</h2><label>Keyword<input onChange={(e) => setQuery(e.target.value)} placeholder="authentication" type="search" value={query}/></label><label>Evidence<select onChange={(e) => setEvent(e.target.value)} value={event}><option value="ALL">All evidence</option><option value="ROUTE">Route</option><option value="DEPENDENCY">Dependency</option></select></label></aside><section aria-labelledby="timeline-title"><p className="eyebrow">timeline / newest first</p><h2 id="timeline-title">Observable transitions</h2>{visible.length ? <div className="commits">{visible.map((commit) => <article className="commit" key={commit.sha}><div className="commitSha"><code>{commit.shortSha}</code><br/>{new Date(commit.committedAt).toLocaleDateString("en-GB", { day:"2-digit", month:"short", year:"numeric" })}</div><div><h3><Link href={`/repositories/demo/commits/${commit.shortSha}`}>{commit.message}</Link></h3><span className="tag">{commit.category.toLowerCase()}</span><ul className="events">{commit.routeChanges.map((change) => <li key={change.route}><span className={change.type === "ADDED" ? "add" : "remove"}>{change.type === "ADDED" ? "+ route" : "- route"}</span> <code>{change.route}</code></li>)}{commit.dependencyChanges.map((change) => <li key={`${change.type}-${change.packageName}`}><span className={change.type === "ADDED" ? "add" : change.type === "REMOVED" ? "remove" : "update"}>{change.type === "ADDED" ? "+ dependency" : change.type === "REMOVED" ? "- dependency" : "~ dependency"}</span> <code>{change.packageName}</code> {change.previousValue && change.currentValue ? `${change.previousValue} to ${change.currentValue}` : change.currentValue ?? change.previousValue}</li>)}</ul><details><summary>Show {commit.files.length} changed files</summary><ul className="fileList">{commit.files.map((file) => <li key={file.path}>{file.status} · {file.path}</li>)}</ul></details></div><div className="commitStats">{commit.statistics.changedFiles} files<br/><span className="add">+{commit.statistics.additions}</span> <span className="remove">-{commit.statistics.deletions}</span></div></article>)}</div> : <div className="emptyState"><strong>No commits match these filters.</strong><button className="button" onClick={() => {setQuery("");setEvent("ALL");}} type="button">Clear filters</button></div>}</section></div>;
}
