export const errorCodes = [
  "INVALID_REPOSITORY_URL",
  "REPOSITORY_NOT_FOUND",
  "REPOSITORY_NOT_PUBLIC",
  "EMPTY_REPOSITORY",
  "UNSUPPORTED_REPOSITORY",
  "REPOSITORY_LIMIT_EXCEEDED",
  "GITHUB_DATA_TRUNCATED",
  "GITHUB_RATE_LIMITED",
  "GITHUB_UNAVAILABLE",
  "IMPORT_RATE_LIMITED",
  "CONFIGURATION_REQUIRED",
  "INVALID_APP_ROOT_SELECTION",
  "RUN_NOT_FOUND",
  "RUN_NOT_CONFIGURABLE",
  "RUN_ALREADY_ACTIVE",
  "RUN_NOT_RETRYABLE",
  "CURSOR_INVALID",
  "CURSOR_SNAPSHOT_MISMATCH",
  "PROCESSING_FAILED",
  "ADMIN_UNAUTHORIZED",
] as const;

export type ErrorCode = (typeof errorCodes)[number];
